on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy server
        uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
